import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from '@react-oauth/google';
const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "react-hot-toast";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GoogleOAuthProvider clientId="764704278433-f8tkf5ei6vgpijj5tfhbns5re5fl78tg.apps.googleusercontent.com">
        <body className={inter.className}>{children}</body>
        <Toaster/>
      </GoogleOAuthProvider>
    </html>
  );
}
